
services:
  db:
    image: postgres:17.5
    container_name: movies_db_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file: .env
    volumes:
      - movies_db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  
  redis:
    image: redis:latest
    container_name: movies_redis_container
    env_file: .env
    volumes:
      - movies_redis_data:/data
    ports:
      - 6379:6379
    
  web:
    container_name: movies_web_container
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # broker port
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  celery_worker:
    container_name: movies_celery_worker
    build: .
    command: celery -A recommendation_system worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq

  celery_beat:
    container_name: movies_celery_beat
    build: .
    command: celery -A recommendation_system beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq

volumes:
  movies_db_data:
  movies_redis_data: